enable to use wildcard in access_token's group
jfrog/terraform-provider-artifactory pull request #208
Opened 2021-11-11 03:41 UTC by cappyzawa

The wildcard is allowed in groups attribute of access_token resource.
However, an error occurs because there is no group named `*`.

2021-11-11 17:31 UTC, chb0github commented on pkg/artifactory/resource_artifactory_access_token_test.go
> +const wildcardGroupGood = `
Please format the string properly and include it in the test. This isn't a sharable string

2021-11-12 02:07 UTC, cappyzawa commented on pkg/artifactory/resource_artifactory_access_token.go
> +			if !exist && groups[i] != "*" {
You're right.
I'll fix it.

2021-11-12 19:39 UTC, chb0github commented on pkg/artifactory/resource_artifactory_access_token.go
> +				if exist, err := checkGroupExists(client, groups[i]); !exist {
This isn't quite right. On `err` return err. On `!exists` well, that is also an error but a totally different kind. And, I realize that the original logic did this, but I can see now that it is wrong.  I am going to look at the code now holistically

2021-11-12 19:44 UTC, chb0github commented on pkg/artifactory/resource_artifactory_access_token.go
> +				if exist, err := checkGroupExists(client, groups[i]); !exist {
yeah, even thought it isn't something you wrote, I now see this as a bug. So, if you could make a change and test, that'd be great.

```go
exist, err := checkGroupExists(client, groups[i])
if err {
   return err
}
if !exist {
   return fmt.Errorf("group %s doesn't exist",group)
}
```

If not, we can accept as is and I can ask a team member to make this change

2021-11-12 19:44 UTC, chb0github requested changes
Sorry, one last change request

2021-11-12 21:09 UTC, chb0github commented on pkg/artifactory/resource_artifactory_access_token.go
> +				if exist, err := checkGroupExists(client, groups[i]); !exist {
Ok, looking at this implementation of this `checkGroupExists` and it seems that 
`!exists == (err != nil)`
So, although I hate the optics here. It works. @alexhung We can probably merge

2021-11-12 21:28 UTC, merged