GH-295 Fix priority_resolution attribute for npm, cargo, docker, helm…
jfrog/terraform-provider-artifactory pull request #316
Opened 2022-02-12 00:22 UTC by maheshjfrog

… remote repositories
Fixes: #295

2022-02-12 00:31 UTC, alexhung requested changes
Code looks good. Missing CHANGELOG.md though 😄

2022-02-12 00:33 UTC, maheshjfrog commented
> 

Will add the CHANGELOG.md

2022-02-12 02:42 UTC, chb0github commented on pkg/artifactory/resource_artifactory_remote_pypi_repository.go
> +	RepositorySuffix string `hcl:"pypi_repository_suffix" json:"pyPIRepositorySuffix"`
Is there a reason no one allows the default packer to general the hcl?

2022-02-12 02:42 UTC, chb0github commented on pkg/artifactory/resource_artifactory_remote_pypi_repository.go
> +		ValidateFunc: validation.IsURLWithHTTPorHTTPS,
Please use the new `ValidateDiagFunc`

2022-02-12 02:42 UTC, chb0github requested changes
see comments

2022-02-14 16:52 UTC, alexhung approved these changes

2022-02-14 16:53 UTC, merged