artifactory_general_security documentation note
jfrog/terraform-provider-artifactory pull request #367
Opened 2022-03-21 23:00 UTC by dasmanas

artifactory_general_security documentation note improved.

2022-03-21 23:36 UTC, danielmkn submitted a review, later dismissed

2022-03-22 01:00 UTC, chb0github commented on docs/resources/artifactory_general_security.md
> +**NOTE:** The artifactory_general_security resource uses endpoints those are undocumented and may not work with SaaS
That are not...

2022-03-22 01:01 UTC, chb0github requested changes
Grammar change

2022-03-22 17:51 UTC, chb0github submitted a review, later dismissed

2022-03-28 21:29 UTC, alexhung requested changes
Looks good to me. Need to update the changelog before we can merge.

In future, please don't leave PR stale for this long.

2022-03-29 15:59 UTC, alexhung requested changes

2022-03-29 15:59 UTC, alexhung commented on CHANGELOG.md
> +## 2.24.1 (Mar 21, 2022)
Need to be updated

2022-03-30 18:53 UTC, alexhung approved these changes

2022-03-30 18:55 UTC, dasmanas commented on CHANGELOG.md
> +## 2.24.1 (Mar 21, 2022)
fixed

2022-03-30 19:01 UTC, maheshjfrog approved these changes

2022-03-30 19:04 UTC, chb0github requested changes
Grammar change

2022-03-30 19:14 UTC, dasmanas commented
> Grammar change

done

2022-03-30 19:27 UTC, alexhung approved these changes

2022-03-31 22:53 UTC, alexhung approved these changes

2022-03-31 22:54 UTC, chb0github approved these changes

2022-03-31 22:55 UTC, maheshjfrog approved these changes

2022-03-31 22:56 UTC, merged