GH-347 remote maven repo password always update
jfrog/terraform-provider-artifactory pull request #385
Opened 2022-04-01 22:59 UTC by alexhung

Fixes #347

- Remove hashing of remove repo ‘password’ attribute
- Remove ‘omitempty’ tag for the same
- Add `noPassword` predicate and `noPasswordPacker` packer so the value from Artifactory API is ignored for TF state.

2022-04-01 23:01 UTC, alexhung commented
This doesn't conflict or change #380 so we can merge this before #380.

2022-04-01 23:23 UTC, danielmkn approved these changes

2022-04-01 23:27 UTC, maheshjfrog approved these changes

2022-04-04 15:55 UTC, chb0github submitted a review, later dismissed
No real requests for changes, just a suggestion. I would love to understand this issue a little better

2022-04-04 16:20 UTC, dasmanas submitted a review, later dismissed

2022-04-04 18:14 UTC, alexhung commented on pkg/artifactory/resource_artifactory_remote_cocoapods_repository.go
> +	return mkResourceSchema(cocoapodsRemoteSchema, noPasswordPacker, unpackCocoapodsRemoteRepo, func() interface{} {
Yea, I see the other way of composing the packer with `inSchema` but I wasn't sure I need to here (as well as not wanting to make too big changes).

2022-04-04 18:35 UTC, alexhung commented
@chb0github Replaced `noPasswordPacker` with your suggestion.

2022-04-04 19:02 UTC, chb0github commented on pkg/artifactory/resource_artifactory_remote_go_repository.go
> +	goRemoteRepoPacker := universalPack(
How about a default packer that takes an argument that is the schema?

2022-04-04 19:02 UTC, chb0github requested changes
Too much CP

I think what you've done could replace the default packer

2022-04-04 21:32 UTC, chb0github commented on pkg/artifactory/repositories.go
> +	if skeema != nil && len(skeema) > 0 {
I think `len(skeema)` handles nil

2022-04-04 21:45 UTC, alexhung commented on pkg/artifactory/repositories.go
> +	if skeema != nil && len(skeema) > 0 {
Unfortunately, it doesn't.

2022-04-04 22:27 UTC, chb0github commented on pkg/artifactory/repositories.go
> +var defaultPacker = universalPack(nil, noClass)
I was thinking something more like:

```go
func defaultPacker(skeema map[string]*schema) {
   return univeralPack(hasKey(skeema,noPassword))
}
```

And then not have this code in the universalPack - I think it's unwise to cook that in
}

2022-04-05 21:46 UTC, chb0github approved these changes

2022-04-05 21:50 UTC, merged