Add support for release bundles for permission targets
jfrog/terraform-provider-artifactory pull request #454
Opened 2022-05-10 23:12 UTC by neilvana

To resolve #449, add support for release bundles to `artifactory_permission_target`.  Previously the schema already supported specifying a `release_bundle` block but the pack and unpack methods lacked the capability to operate on the block.  Implement the required logic, add documentation and augment test cases.

I tested I was able to create a new permission target including release bundle permissions on our Enterprise+ SaaS instance of Artifactory.  I have not yet run the acceptance tests since I have yet to set up a test Artifactory server. Would it be possible to run these tests on JFrog's infrastructure or do I need to set up my own trial instances of Artifactory to validate the tests?

2022-05-10 23:17 UTC, alexhung commented
@neilvana Thanks for the PR! The PR will be run through our CI system so we will know soon.

2022-05-10 23:17 UTC, alexhung commented
@chb0github ☝🏼

2022-05-10 23:17 UTC, neilvana commented
I'm working on getting the CLA signed.

2022-05-11 03:38 UTC, chb0github commented on pkg/artifactory/resource/security/resource_artifactory_permission_target_test.go
> +	//resource "artifactory_local_docker_repository" "{{ .repo_name }}" {
Remove commented out code

2022-05-11 07:06 UTC, martinm82 commented
Thanks a lot for this PR. The perfect moment as we started to use recently the provider and release bundles 💯

2022-05-11 13:56 UTC, neilvana commented on pkg/artifactory/resource/security/resource_artifactory_permission_target_test.go
> +	//resource "artifactory_local_docker_repository" "{{ .repo_name }}" {
Done.

2022-05-11 15:54 UTC, alexhung commented
@neilvana Got the test results from our CI. I'll look into this and see if I can fix this on my end and get the tests pass locally.

```
=== RUN   TestAccPermissionTarget_addBuild
    resource_artifactory_permission_target_test.go:243: Step 4/4 error: Error running pre-apply refresh: exit status 1
        
        Error: Invalid multi-line string
        
          on terraform_plugin_test.tf line 49, in resource "artifactory_permission_target" "test-perm199069":
          49: 		excludes_pattern = ["bar/**]
          50: 		repositories     = ["release-bundles"]
        
        Quoted strings may not be split over multiple lines. To produce a multi-line
        string, either use the \n escape to represent a newline character or use the
        "heredoc" multi-line template syntax.
        
        Error: Unterminated template string
        
          on terraform_plugin_test.tf line 49, in resource "artifactory_permission_target" "test-perm199069":
          49: 		excludes_pattern = ["bar/**]
          50: 		repositories     = ["release-bundles"]
        
        No closing marker was found for the string.
        
        Error: Invalid multi-line string
        
          on terraform_plugin_test.tf line 50, in resource "artifactory_permission_target" "test-perm199069":
          50: 		repositories     = ["release-bundles"]
          51: 		actions {
        
        Quoted strings may not be split over multiple lines. To produce a multi-line
        string, either use the \n escape to represent a newline character or use the
        "heredoc" multi-line template syntax.
        
        Error: Invalid multi-line string
        
          on terraform_plugin_test.tf line 52, in resource "artifactory_permission_target" "test-perm199069":
          52: 		actions {
          53: 			users {
        
        Quoted strings may not be split over multiple lines. To produce a multi-line
        string, either use the \n escape to represent a newline character or use the
        "heredoc" multi-line template syntax.
        
        Error: Invalid multi-line string
        
          on terraform_plugin_test.tf line 53, in resource "artifactory_permission_target" "test-perm199069":
          53: 			users {
          54: 				name        = "anonymous"
        
        Quoted strings may not be split over multiple lines. To produce a multi-line
        string, either use the \n escape to represent a newline character or use the
        "heredoc" multi-line template syntax.
        
        Error: Invalid multi-line string
        
          on terraform_plugin_test.tf line 54, in resource "artifactory_permission_target" "test-perm199069":
          54: 				name        = "anonymous"
          55: 				permissions = ["read", "write"]
        
        Quoted strings may not be split over multiple lines. To produce a multi-line
        string, either use the \n escape to represent a newline character or use the
        "heredoc" multi-line template syntax.
        
        Error: Invalid multi-line string
        
          on terraform_plugin_test.tf line 55, in resource "artifactory_permission_target" "test-perm199069":
          55: 				permissions = ["read", "write"]
          56: 			}
        
        Quoted strings may not be split over multiple lines. To produce a multi-line
        string, either use the \n escape to represent a newline character or use the
        "heredoc" multi-line template syntax.
        
        Error: Invalid multi-line string
        
          on terraform_plugin_test.tf line 56, in resource "artifactory_permission_target" "test-perm199069":
          56: 			}
          57: 			groups {
        
        Quoted strings may not be split over multiple lines. To produce a multi-line
        string, either use the \n escape to represent a newline character or use the
        "heredoc" multi-line template syntax.
        
        Error: Invalid multi-line string
        
          on terraform_plugin_test.tf line 59, in resource "artifactory_permission_target" "test-perm199069":
          59: 			groups {
          60: 				name        = "readers"
        
        Quoted strings may not be split over multiple lines. To produce a multi-line
        string, either use the \n escape to represent a newline character or use the
        "heredoc" multi-line template syntax.
        
        Error: Invalid multi-line string
        
          on terraform_plugin_test.tf line 60, in resource "artifactory_permission_target" "test-perm199069":
          60: 				name        = "readers"
          61: 				permissions = ["read"]
        
        Quoted strings may not be split over multiple lines. To produce a multi-line
        string, either use the \n escape to represent a newline character or use the
        "heredoc" multi-line template syntax.
        
        Error: Invalid multi-line string
        
          on terraform_plugin_test.tf line 61, in resource "artifactory_permission_target" "test-perm199069":
          61: 				permissions = ["read"]
          62: 			}
        
        Quoted strings may not be split over multiple lines. To produce a multi-line
        string, either use the \n escape to represent a newline character or use the
        "heredoc" multi-line template syntax.
        
        Error: Invalid multi-line string
        
          on terraform_plugin_test.tf line 62, in resource "artifactory_permission_target" "test-perm199069":
          62: 			}
          63: 		}
        
        Quoted strings may not be split over multiple lines. To produce a multi-line
        string, either use the \n escape to represent a newline character or use the
        "heredoc" multi-line template syntax.
        
        Error: Invalid multi-line string
        
          on terraform_plugin_test.tf line 63, in resource "artifactory_permission_target" "test-perm199069":
          63: 		}
          64: 	  }
        
        Quoted strings may not be split over multiple lines. To produce a multi-line
        string, either use the \n escape to represent a newline character or use the
        "heredoc" multi-line template syntax.
        
        Error: Invalid multi-line string
        
          on terraform_plugin_test.tf line 64, in resource "artifactory_permission_target" "test-perm199069":
          64: 	  }
          65:      //depends_on = [artifactory_local_docker_repository.example-repo-local]
        
        Quoted strings may not be split over multiple lines. To produce a multi-line
        string, either use the \n escape to represent a newline character or use the
        "heredoc" multi-line template syntax.
        
        Error: Invalid multi-line string
        
          on terraform_plugin_test.tf line 65, in resource "artifactory_permission_target" "test-perm199069":
          65:      //depends_on = [artifactory_local_docker_repository.example-repo-local]
          66: 	}
        
        Quoted strings may not be split over multiple lines. To produce a multi-line
        string, either use the \n escape to represent a newline character or use the
        "heredoc" multi-line template syntax.
        
        Error: Invalid multi-line string
        
          on terraform_plugin_test.tf line 66, in resource "artifactory_permission_target" "test-perm199069":
          66: 	}
        
        Quoted strings may not be split over multiple lines. To produce a multi-line
        string, either use the \n escape to represent a newline character or use the
        "heredoc" multi-line template syntax.
    testing_new.go:72: Error retrieving state, there may be dangling resources: exit status 1
        
        Error: Invalid multi-line string
        
          on terraform_plugin_test.tf line 49, in resource "artifactory_permission_target" "test-perm199069":
          49: 		excludes_pattern = ["bar/**]
          50: 		repositories     = ["release-bundles"]
        
        Quoted strings may not be split over multiple lin [...]

2022-05-11 15:54 UTC, alexhung requested changes
Tests failed

2022-05-11 18:23 UTC, chb0github submitted a review, later dismissed
I tests are passing, @alexhung I am ok with this

2022-05-11 19:42 UTC, chb0github commented on pkg/artifactory/resource/security/resource_artifactory_permission_target_test.go
> +		excludes_pattern = ["bar/**"]
Oopa

2022-05-11 19:43 UTC, neilvana commented
I missed a quote in the test template 🤦  It should be fixed now.  Would it be possible to run the CI tests again?

2022-05-11 20:26 UTC, alexhung commented
@neilvana Tests pass in CI.

2022-05-11 20:26 UTC, alexhung approved these changes
:shipit:

2022-05-11 21:58 UTC, chb0github approved these changes

2022-05-11 22:01 UTC, alexhung commented
I'll merge this after #456 and #453

2022-05-11 23:16 UTC, alexhung commented
@neilvana Any progress on signing the CLA?

2022-05-12 00:46 UTC, neilvana commented
Hopefully by tomorrow.  I'm waiting on Legal.  Since this is the first contribution from our organization to JFrog repos it is taking a bit longer.  Sorry for the delay.  I'll try to hurry it up.

2022-05-12 00:54 UTC, danielmkn approved these changes

2022-05-12 15:00 UTC, neilvana commented
I have read the CLA Document and I hereby sign the CLA

2022-05-12 16:06 UTC, merged