Added data source support for the user resource.
jfrog/terraform-provider-artifactory pull request #611
Opened 2022-12-22 21:09 UTC by Turhsus

There is only 1 test case since all this is a simple fetch. I'm not sure what else we could/should test for these types of get requests.

2022-12-22 23:07 UTC, alexhung requested changes

2022-12-22 23:10 UTC, Turhsus commented on pkg/artifactory/datasource/datasource_artifactory_group.go
> +func DataSourceArtifactoryGroup() *schema.Resource {
I thought so too, but then I was caught between that and following the convention establish for resources where it had the Resource at the start of it. What do you think is better here? Leaving out the 'DataSource`?

2022-12-22 23:11 UTC, Turhsus commented on pkg/artifactory/datasource/user/datasource_artifactory_user.go
> +		d.SetId("name")
Wow can't believe I did this! Can we write a test case to make sure the id is set correctly?

2022-12-22 23:11 UTC, Turhsus commented on pkg/artifactory/datasource/user/datasource_artifactory_user.go
> +		Description: "placeholder",
Added with docs commit

2022-12-22 23:12 UTC, Turhsus commented on pkg/artifactory/datasource/user/user.go
> +package user
Its just future infrastructure, there are 3 more "types" of user resources that might become data sources in the future, thought I'd leave a package wide defining file here. I also thought about defining the schema in this file? What do you think

2022-12-22 23:13 UTC, alexhung commented on pkg/artifactory/datasource/datasource_artifactory_group.go
> +func DataSourceArtifactoryGroup() *schema.Resource {
Ah I see. I guess that's ok then to have the prefix.

2022-12-22 23:13 UTC, Turhsus commented on pkg/artifactory/datasource/user/datasource_artifactory_user.go
> +var userSchema = map[string]*schema.Schema{
I tried to use the util.MergeMaps schema and doing it that way, but I needed to change "email" from required to optional and that was changing it in both maps. Will ook into this further enxt week.

2022-12-22 23:14 UTC, alexhung commented on pkg/artifactory/datasource/user/datasource_artifactory_user.go
> +		d.SetId("name")
You should be able to check the `Id` field in the test, I think?

2022-12-22 23:15 UTC, alexhung commented on pkg/artifactory/datasource/user/user.go
> +package user
Yes, but let's not have premature optimization. So no need for this file, until you actually is using it.

2023-01-03 22:31 UTC, alexhung requested changes
A few tidy up to do. Almost there.

2023-01-03 22:31 UTC, alexhung commented on docs/data-sources/artifactory_user.md
> +# Artifactory Group Data Source
s/Group/User

2023-01-03 22:31 UTC, alexhung commented on pkg/artifactory/datasource/user/datasource_artifactory_user.go
> +var userSchema = map[string]*schema.Schema{
Let's move this variable into `DataSourceArtifactoryUser()` so it's scoped within that function.

2023-01-03 22:31 UTC, alexhung commented on pkg/artifactory/datasource/user/datasource_artifactory_user.go
> +		userObj := &user.User{}
Let's not use `&` here (should use it in `SetResult()` instead). This create inconsistency with `userObj` not actually an instance of the struct but the address of the struct.

2023-01-03 22:31 UTC, alexhung commented on pkg/artifactory/datasource/user/datasource_artifactory_user.go
> +		return user.PackUser(*userObj, rd)
See how you have to dereference `userObj` here? Not great. Yes, the code in `user.go` is wrong also.

2023-01-03 22:31 UTC, alexhung commented on pkg/artifactory/provider/provider.go
> +				"artifactory_group":    datasource.DataSourceArtifactoryGroup(),
Since we are setting package name with the path name (e.g. `datasource_user`), let's update this to `datasource_group` as well.

2023-01-03 22:31 UTC, alexhung commented on pkg/artifactory/resource/user/user.go
>  	user := &User{}
I know this is from previous commit. Let's update this to not use `&` here.

2023-01-05 23:07 UTC, alexhung approved these changes
:shipit:

2023-01-05 23:27 UTC, alexhung approved these changes

2023-01-06 22:15 UTC, danielmkn approved these changes
LGTM

2023-01-06 22:16 UTC, merged