GH-602 user resource deprecation
jfrog/terraform-provider-artifactory pull request #622
Opened 2023-01-12 19:57 UTC by danielmkn

2023-01-12 20:40 UTC, alexhung requested changes
Please work with Shailendra and determine the appropriate deprecation period (6 months?).

I'd also recommend creating a new discussion thread in https://github.com/jfrog/terraform-provider-artifactory/discussions and ask the users in previous [Password Issue](https://github.com/jfrog/terraform-provider-artifactory/discussions/333) discussion.

2023-01-12 20:40 UTC, alexhung commented on CHANGELOG.md
> +* resource/artifactory_user and resource/artifactory_unmanaged_user: added deprecation notice. Both resources are deprecated in favor of resource/artifactory__managed_user.
There's an extra underscore in `artifactory_managed_user`.

2023-01-12 21:20 UTC, danielmkn commented
Discussion is here - #623

2023-01-12 21:29 UTC, Turhsus approved these changes
Other than the deprecation period, LGTM

2023-01-13 19:33 UTC, danielmkn commented
There are a bunch of tests, using `artifactory_user` without the password provided. We will have to replace them before the merge if it will be decided to proceed.

2023-01-18 21:16 UTC, danielmkn commented
We won't deprecate the resource, based on the conversation with our users. I'll update the documentation instead in a separate PR.

2023-01-18 21:16 UTC, closed without merging