adds reference token to scoped token creation if requested
jfrog/terraform-provider-artifactory pull request #723
Opened 2023-04-24 07:49 UTC by bb-Ricardo

This will add the reference token the resource output fields if requested.

2023-04-24 17:36 UTC, alexhung commented on CHANGELOG.md
> +## 7.6.1 (XXX XX, 2023). Tested on Artifactory 7.55.10
Should be bumped to 7.7.0 due to new attribute

2023-04-24 17:37 UTC, alexhung requested changes
Version changes in CHANGELOG

2023-04-25 18:09 UTC, alexhung approved these changes

2023-04-25 19:45 UTC, danielmkn requested changes
A couple of minor changes are needed.

2023-04-25 19:45 UTC, danielmkn commented on CHANGELOG.md
> +* resource/artifactory_scoped_token: adds reference token exposure on scoped token creation
* resource/artifactory_scoped_token: adds `reference_token` attribute for the resource.

2023-04-25 19:45 UTC, danielmkn commented on pkg/artifactory/resource/security/resource_artifactory_scoped_token.go
> +		},
Please add description here as well: 
```
Description: "Should a reference token also be created? Defaults to `false`",

2023-04-25 19:45 UTC, danielmkn commented on CHANGELOG.md
> +## 7.7.0 (XXX XX, 2023). Tested on Artifactory 7.55.10
```
## 7.7.0 (April 26, 2023). Tested on Artifactory 7.55.10

2023-04-25 19:49 UTC, danielmkn requested changes

2023-04-25 19:49 UTC, danielmkn commented on pkg/artifactory/resource/security/resource_artifactory_scoped_token.go
> +			Description: "Also create a reference token which can be used like an API key.",
Please add:
```
Default is `false`.

2023-04-25 19:49 UTC, danielmkn commented on pkg/artifactory/resource/security/resource_artifactory_scoped_token.go
> +		},
PLease add 
```
Description: "Reference Token (alias to Access Token)",

2023-04-28 18:12 UTC, danielmkn approved these changes

2023-04-28 18:13 UTC, merged