Migrate permission target to framework
jfrog/terraform-provider-artifactory pull request #742
Opened 2023-05-31 21:44 UTC by alexhung

* Migrate artifactory_permission_target to plugin framework
* Remove deprecated `artifactory_permission_targets` resource from SDKv2 provider
* DRY the error handling function and move to shared module

2023-05-31 23:37 UTC, shrajfr12 submitted a review, later dismissed
lgtm

2023-06-01 18:07 UTC, danielmkn requested changes
Minor changes required.

2023-06-01 18:07 UTC, danielmkn commented on pkg/artifactory/resource/security/resource_artifactory_permission_target.go
> +			validatorfw.RequireIfDefined(path.Expressions{ // use customer validator to ensure 'repositories' attribute is set if this block is defined in configuration. See https://github.com/hashicorp/terra
customer -> custom

2023-06-01 18:07 UTC, danielmkn commented on pkg/artifactory/resource/security/resource_artifactory_permission_target.go
> +		resp.Diagnostics.AddError(
You can replace it with `utilfw.UnableToDeleteResourceError(resp, err)`

2023-06-01 18:07 UTC, danielmkn commented on pkg/artifactory/resource/security/resource_artifactory_permission_target.go
> +		resp.Diagnostics.AddError(
Same here.

2023-06-01 18:08 UTC, danielmkn requested changes
Minor changes required.

2023-06-01 18:09 UTC, alexhung commented on pkg/artifactory/provider/framework.go
> +		user.NewUserResource,
Sure. I didn't remove since this is a func to create new resource. So that kinda make sense.

2023-06-01 19:27 UTC, danielmkn approved these changes
Minor changes required.

2023-06-01 20:07 UTC, merged