Adds support for adding users to groups
jfrog/terraform-provider-artifactory pull request #99
Opened 2021-08-04 22:48 UTC by ax-taustgen

The jfrog api currently supports updating groups with the list of users that belong to that group. This adds the same functionality to terraform.

Previously was using the atlassian artifactory plugin which is 2 years out of date and lacking features, I updated it to use the new jfrog owned client which is currently maintained.

State of repository means tests cannot currently be run

2021-08-04 22:52 UTC, ax-taustgen commented
I have read the CLA Document and I hereby sign the CLA

2021-08-04 22:59 UTC, ax-taustgen commented
@chb0github Could use advice with the following two questions, 
1. Is it possible to retrigger the github action  without pushing a no-op commit, I don't have high enough permissions on this repo to restart the workflow from the UI

2. How are we supposed to run the test suite, the README mentions a docker-compose file but currently it doesnt exist and the makefile lists test as broken

2021-08-04 23:11 UTC, ax-taustgen commented
I've run a make test but since I'm having to replace the client I really would like to run an integration test against a local instance, but it looks like that functionality is currently working

2021-08-12 17:20 UTC, chb0github commented
Any updates?

2021-08-16 17:43 UTC, chb0github commented
If you can finish this soon, that'd be great. It's next up on my migration path from the atlassian client

2021-08-16 20:58 UTC, ax-taustgen commented
@chb0github This is ready for review now, I found a work around for UpdateGroup using POST instead of PUT and preventing disassociating users because of it. 


```
=== RUN   TestAccGroup_basic
--- PASS: TestAccGroup_basic (3.26s)
=== RUN   TestAccGroup_full
--- PASS: TestAccGroup_full (10.85s)
```

2021-08-17 18:32 UTC, chb0github commented on pkg/artifactory/resource_artifactory_group.go
> +	group, err := resourceGroupGet(d, m)
I don't know why the original status code check was there, but I am not comfortable removing it without an explanation

2021-08-17 18:35 UTC, chb0github commented on pkg/artifactory/resource_artifactory_group_test.go
> +		if resp.StatusCode == http.StatusNotFound {
If you don't initially check `err`, then you have no guarantee that `resp` isn't`nil` - So, please check that `resp != nil` - I've had this cause me crashes

2021-08-17 18:35 UTC, chb0github commented on pkg/artifactory/resource_artifactory_group_test.go
>  		_, resp, err := client.V1.Security.GetGroup(context.Background(), rs.Primary.ID)
You're still using the old atlassian client to test?

2021-08-17 18:37 UTC, chb0github requested changes
Please address these few things. This is pretty close

2021-08-18 23:42 UTC, ax-taustgen commented
Could use a rereview when you get a minute

2021-08-19 17:05 UTC, chb0github commented
I think I am ok with what I see here. However, I have been removing all atlassian references and putting them into an entirely different branch and will release them all as a major version bump. When do you need to see this in a release?

2021-08-19 17:06 UTC, chb0github reviewed
I am ok with what I see, but I want to hold off on a release because I want to do a major version bump when all atlassian code is gone.

2021-08-19 17:12 UTC, ax-taustgen commented
I would really prefer to get this available, its a blocker for rolling out artifactory to my product teams.  I could maybe wait a sprint, but I've got a cutover coming up soon and really don't want have to manually provision it all.

2021-08-19 21:51 UTC, chb0github commented
How about: Come hell-or-highwater, the end of this month 2.3.1 is released?

2021-08-20 16:47 UTC, ax-taustgen commented
👍  sooner is better than later but if you can get it done before September, I can probably make it work

2021-08-23 16:34 UTC, ax-taustgen commented
Can you approve this so I can merge? Or are there more changes needed still?

2021-08-23 20:03 UTC, merged

2021-08-23 20:04 UTC, chb0github commented
I merged it. I will let you know when it releases

2021-08-23 21:13 UTC, ax-taustgen commented
Thank you!

2021-09-03 16:55 UTC, ax-taustgen commented
Hows 2.3.1 coming?

2021-09-07 17:57 UTC, chb0github commented
Going out today. Sorry. I am just seeing this. I got additional crap
dropped in my plate. It's going out with sdk2 and I am exhausted from
looking at this code. But, I have a way clearer understanding of it. Most
of the tests pass - 1 can't pass and another requires implementation of
retry logic.

On Fri, Sep 3, 2021 at 9:56 AM ax-taustgen ***@***.***> wrote:

> Hows 2.3.1 coming?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/jfrog/terraform-provider-artifactory/pull/99#issuecomment-912677558>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALIRUCMZPFF6HI7JGTJPWTUAD4Z5ANCNFSM5BSF2ZMA>
> .
>

2021-09-08 20:27 UTC, chb0github commented
released

On Tue, Sep 7, 2021 at 10:57 AM Christian Bongiorno ***@***.***>
wrote:

> Going out today. Sorry. I am just seeing this. I got additional crap
> dropped in my plate. It's going out with sdk2 and I am exhausted from
> looking at this code. But, I have a way clearer understanding of it. Most
> of the tests pass - 1 can't pass and another requires implementation of
> retry logic.
>
> On Fri, Sep 3, 2021 at 9:56 AM ax-taustgen ***@***.***>
> wrote:
>
>> Hows 2.3.1 coming?
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/jfrog/terraform-provider-artifactory/pull/99#issuecomment-912677558>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AALIRUCMZPFF6HI7JGTJPWTUAD4Z5ANCNFSM5BSF2ZMA>
>> .
>>
>